import { Inter } from "next/font/google";
import "./globals.css";
import TopNavbar from "./components/common/TopNavbar";
import NewsLetter from "./components/common/NewsLetter";
import Providers from "./redux/Providers";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <TopNavbar />
          {children}
          <div className="mt-20">
            <NewsLetter />
          </div>

        </Providers>
      </body>
    </html>
  );
}
